//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityframeworkkullanımı
{
    using System;
    using System.Collections.Generic;
    
    public partial class arabatablosuDENEME
    {
        public Nullable<int> Id { get; set; }
        public string marka { get; set; }
        public string Renk { get; set; }
        public string Model { get; set; }
        public Nullable<bool> pertmi { get; set; }
        public Nullable<System.DateTime> üretimtarihi { get; set; }
    }
}
